
pr:
  - master

jobs:
  - job: Linux
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'

      - script: npm install

      - script: npm run test:coverage


  - job: macOS
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'

      - script: npm install

      - script: npm run test:coverage


  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'

      - powershell: npm install
      - powershell: npm run test:coverage