name: Node CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [macOS-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install
          npm run test:coverage
        env:
          CI: true
      - name: Update coverage
        if: matrix.os == 'ubuntu-latest'
        run: npm run codecov -- -t ${{ secrets.CODECOV_TOKEN }}
  
  sample-project:
    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - uses: BugDiver/setup-gauge@master


      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install gauge-ts
        if: matrix.os == 'ubuntu-latest'
        run: |
          npm install
          ./build.sh forceinstall

      - name: Install gauge-ts
        if: matrix.os == 'windows-latest'
        run: |
          npm install
          ./build.ps1 forceinstall

      - name: Initialize a sample project
        run: |
          mkdir sample
          cd sample
          gauge init ts

      - name: Run sample project
        run: |
          cd sample
          gauge run specs
