name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        node-version: [ 20.x, 21.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install and test
        run: |
          npm install
          npm run test:coverage
        env:
          CI: true

      
  build-artifacts:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

      - name: Create artifact
        run: |
          ./build.sh package
          npm pack
          mv ./gauge-ts-*.tgz ./artifacts

      - name: Upload artifacts for local
        uses: actions/upload-artifact@v3
        with:
          name: gauge-ts
          path: ./artifacts

  sample-project:
    needs: build-artifacts
    strategy:
      matrix:
        node-version: [20.x, 21.x]
        os: [macOS-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: BugDiver/setup-gauge@master
        with:
          gauge-version: master

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/download-artifact@v3
        with:
          name: gauge-ts
          path: ./artifacts

      - name: Install gauge-ts
        run: |
          gauge install ts -f ./artifacts/gauge-ts-*.zip
        shell: bash

      - name: Initialize a sample project
        run: |
          mkdir sample
          cd sample
          gauge init https://github.com/bockstaller/template-ts/releases/latest/download/ts.zip
          npm install ../artifacts/gauge-ts-*.tgz
        shell: bash

      - name: Run sample project
        run: |
          cd sample
          gauge run specs
